### ISSUE TITLE
Is there any way to find the shortest path among two TreeNodes?

### ISSUE THREAD

**Issue by fighting41love** [EmilStenstrom/conllu#10]
The TreeNode is an OrderedDict.
Question: Is there any way to find the shortest path among two TreeNodes?
Thanks!

**Comment by EmilStenstrom** [comment]
Hi! There's currently no way to do that. The code for the TreeNode is extremely bare-bones, you can find it here: https://github.com/EmilStenstrom/conllu/blob/master/conllu/tree_helpers.py

If you have a common enough use-case for this, that I have missed, I would be happy to include it in the library.
