### ISSUE TITLE
undocumented breaking change from 0.1 to 1.0

### ISSUE THREAD

**Issue by DeNeutoy** [EmilStenstrom/conllu#15]
Thanks for the exceptional library - just wanted to note a breaking change we ran into which wasn't documented:

https://github.com/EmilStenstrom/conllu/blob/master/conllu/parser.py#L117

Previously I was relying on float `id` values being parsed as `None`, which occurs for words which have been elided in the text, but automatically reconstructed in the annotations. This line now parses the id as the id of the word which it elides. If you were using this field to check for elipsis, you should now check whether the `head` field is `None` instead.

**Comment by EmilStenstrom** [comment]
Thanks for this gotcha, I'm sure it will help someone else upgrade. I've added documentation of this to the [migrations document in the wiki](https://github.com/EmilStenstrom/conllu/wiki/Migrating-from-0.1-to-1.0#parsing-of-ids-now-include-ranges-and-decimals). I opted for another fix, to check the that the id is an integer (all other types are tuples), but I think it does the same as checking the head element against None.
