### ISSUE TITLE
TokenList could inherit "list"

### ISSUE THREAD

**Issue by bryant1410** [EmilStenstrom/conllu#18]
Hey. I have found this library quite useful. There is a suggestion that I ran into: `TokenList` could maybe inherit `list`, and so be treated like that.

I tried manipulating the sentences (TokenLists) as if they were lists, such as using `len` but then I saw they weren't. I thought about adding `__len__`, but I think it's more appropriate to make them lists, so they natively support other things such as adding them, comparing them, and so on.

What do you think guys?

**Comment by EmilStenstrom** [comment]
Hi @bryant1410! This sounds like an interesting idea. I'd say TokenList is an extension to a list, so inheriting from there feels natural. 

I'm definitely open to a PR making this happen! Please make sure no tests fail if you try it, you can just type `tox` in the root directory after cloning to run all the tests.

**Comment by EmilStenstrom** [comment]
Oh, and I'd like this lib to be open to people that are [not "guys"](https://subfictional.com/language-matters-stop-using-guys-to-address-mix-gender-groups/) too :)

**Comment by bryant1410** [comment]
Oh, didn't know "guys" is only males.
