### ISSUE TITLE
Parsing error: Invalid line format, line must contain either tabs or two spaces

### ISSUE THREAD

**Issue by ruathudo** [EmilStenstrom/conllu#23]
Try this dataset: https://github.com/ufal/rh_nntagging/tree/master/data/ud-1.2/en

I got the error when parsing:

`ParseException: Invalid line format, line must contain either tabs or two spaces.`

**Comment by ruathudo** [comment]
Never mind, it is my mistake!

**Comment by EmilStenstrom** [comment]
@ruathudo Thanks for closing the issue when you discovered the error. Just for reference, would you mind writing down what the error was, so that someone else with the same problem might solve their own problem?

**Comment by goodmami** [comment]
I just had the same problem, and for me the issue was I was passing an open file to `parse()` instead of a string. That is:

```python-console
>>> from conllu import parse
>>> parse(open('ex.conllu'))
Traceback (most recent call last):
[...]
conllu.parser.ParseException: Invalid line format, line must contain either tabs or two spaces.
>>> parse(open('ex.conllu').read())
[TokenList<They, buy, and, sell, books, .>]
```

Hope that helps someone else!

**Comment by EmilStenstrom** [comment]
@goodmami Ah, that is an easy mistake to make. Thanks for posting!

**Comment by LeprechaunSN** [comment]
I've got the following error:
conllu.exceptions.ParseException: Can't create TokenList, no data sent to constructor.

Hope that helps someone else!

**Comment by EmilStenstrom** [comment]
@LeprechaunSN What code where you trying to run?

**Comment by LeprechaunSN** [comment]
@EmilStenstrom Code from documentation:
data = """
# text = The quick brown fox jumps over the lazy dog.
1   The     the    DET    DT   Definite=Def|PronType=Art   4   det     _   _
2   quick   quick  ADJ    JJ   Degree=Pos                  4   amod    _   _
3   brown   brown  ADJ    JJ   Degree=Pos                  4   amod    _   _
4   fox     fox    NOUN   NN   Number=Sing                 5   nsubj   _   _
5   jumps   jump   VERB   VBZ  Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   0   root    _   _
6   over    over   ADP    IN   _                           9   case    _   _
7   the     the    DET    DT   Definite=Def|PronType=Art   9   det     _   _
8   lazy    lazy   ADJ    JJ   Degree=Pos                  9   amod    _   _
9   dog     dog    NOUN   NN   Number=Sing                 5   nmod    _   SpaceAfter=No
10  .       .      PUNCT  .    _                           5   punct   _   _

"""

sentences = parse(data)

**Comment by EmilStenstrom** [comment]
@LeprechaunSN I need a full example file, preferably as a runnable .py file to help you troubleshoot this. The code from the documentation is run each time I run the tests, and tests are passing. So there's something else going on with how you are sending the data to the parse method.
