### ISSUE TITLE
Conllu writer

### ISSUE THREAD

**Issue by erickrf** [EmilStenstrom/conllu#3]
Do you think writing a CoNLLu writer would be easier starting from your current code? Or should I just start one from scratch?

**Comment by EmilStenstrom** [comment]
Hi! I’d love to have a writer as part of this package. One thing that would likely make this easier is to reuse the output format from conllu as the input format for the writer you are proposing. Would you be willing to write up a PR?

**Comment by erickrf** [comment]
Yes, I intend to adapt some of the adhoc code I have and will send a PR.

**Comment by EmilStenstrom** [comment]
Sounds great! Don't forget to add tests! You can run the existing tests with `python setup.py test` in the cloned directory of this repo.

**Comment by EmilStenstrom** [comment]
@erickrf Still have that Ad-hoc code laying around?

**Comment by erickrf** [comment]
I had almost abandoned that project. Now that you mention, I think I can pull something useful out of some code I'm using.

**Comment by erickrf** [comment]
[Sent PR](https://github.com/EmilStenstrom/conllu/pull/5)
