### ISSUE TITLE
CoNLL and sentence headers

### ISSUE THREAD

**Issue by Stormur** [EmilStenstrom/conllu#30]
Since the two formats are nearly identical, can this script read CoNLL? I get errors, probably because the format does not match exactly. 

Could it also read CoNLLU formats where metadata (#-prefixed lines) are missing?

**Comment by EmilStenstrom** [comment]
Can you post a relevant test case here so I can see what errors you get? 

Also, did you see the TestParseConllu2009 test case? https://github.com/EmilStenstrom/conllu/blob/master/tests/test_integration.py#L175

**Comment by Stormur** [comment]
> Also, did you see the TestParseConllu2009 test case? https://github.com/EmilStenstrom/conllu/blob/master/tests/test_integration.py#L175

OK, sorry for the dumb question, what can I do with it?

The file has a list of sentences in the following format:

```
#	id='1'-document_id='36:1047'-span='1'
1	+	+	Punc	Punc	_	0	ROOT	_	_
2	In	in	r	r	r|-|-|-|-|-|-|-|-	5	AuxP	_	_
3	Dei	Deus	n	Propn	n|-|s|-|-|-|m|g|-	4	ATR	_	_
4	nomine	nomen	n	n	n|-|s|-|-|-|n|b|-	2	ADV	_	_
5	regnante	regno	t	t	t|-|s|p|p|a|m|b|-	0	ADV	_	_
6	domno	domnus	n	n	n|-|s|-|-|-|m|b|-	8	ATR	_	_
7	nostro	noster	a	a	a|-|s|-|-|-|m|b|-	6	ATR	_	_
8	Carulo	Carolus	n	Propn	n|-|s|-|-|-|m|b|-	5	SBJ	_	_
9	rege	rex	n	n	n|-|s|-|-|-|m|b|-	8	ATR	_	_
10	Francorum	franci	n	n	n|-|p|-|-|-|m|g|-	11	ATR_CO	_	_
11	et	et	c	c	c|-|-|-|-|-|-|-|-	9	COORD	_	_
12	Langobardorum	langobardi	n	n	n|-|p|-|-|-|m|g|-	11	ATR_CO	_	_
13	,	,	Punc	Punc	_	0	ROOT	_	_
14	anno	annus	n	n	n|-|s|-|-|-|m|b|-	5	ADV	_	_
15	regni	regnum	n	n	n|-|s|-|-|-|n|g|-	14	ATR	_	_
16	eius	is	p	p	p|-|s|-|-|-|m|g|-	15	ATR	_	_
17	quo	qui	p	p	p|-|s|-|-|-|m|b|-	18	ADV	_	_
18	coepit	capio	v	v	v|3|s|r|i|a|-|-|-	14	ATR	_	_
19	Langobardiam	Langobardia	n	Propn	n|-|s|-|-|-|f|a|-	18	OBJ	_	_
20	primo	primus	a	a	a|-|s|-|-|-|m|b|-	14	ATR	_	_
21	,	,	Punc	Punc	_	0	ROOT	_	_
22	septimo	septimus	a	a	a|-|s|-|-|-|m|b|-	23	ATR	_	_
23	decimo	decimus	a	a	a|-|s|-|-|-|m|b|-	5	ADV	_	_
24	kalendas	kalendae	n	n	n|-|p|-|-|-|f|a|-	23	ATR	_	_
25	augustas	augustus	a	a	a|-|p|-|-|-|f|a|-	24	ATR	_	_
26	,	,	Punc	Punc	_	0	ROOT	_	_
27	per	per	r	r	r|-|-|-|-|-|-|-|-	5	AuxP	_	_
28	indictionem	indictio	n	n	n|-|s|-|-|-|f|a|-	27	ADV	_	_
29	duodecimam	duodecimus	a	a	a|-|s|-|-|-|f|a|-	28	ATR	_	_
30	.	.	Punc	Punc	_	0	ROOT	_	_
```

The parse_incr works, but parses a single sentences from the first to the last token of the file (it gives a length of 257918, the file weighs around 13MB).

parse_tree_incr:

```
File "/home/flavio/.local/lib/python3.6/site-packages/conllu/models.py", line 63, in <listcomp>
    for child in head_to_token_mapping[id_]
 File "/home/flavio/.local/lib/python3.6/site-packages/conllu/models.py", line 63, in _create_tree
.
.
.
[repeated hundreds of times]
RecursionError: maximum recursion depth exceeded
```

parse_tree:

```
File "Composita.py", line 38, in <module>
    for sententia in parse_tree(sententiae) : 
  File "/home/flavio/.local/lib/python3.6/site-packages/conllu/__init__.py", line 19, in parse_tree
    tokenlists = parse(data)
  File "/home/flavio/.local/lib/python3.6/site-packages/conllu/__init__.py", line 10, in parse
    for sentence in data.split("\n\n")
  File "/usr/lib/python3.6/codecs.py", line 742, in __getattr__
    return getattr(self.stream, name)
AttributeError: '_io.BufferedReader' object has no attribute 'split'
```

But if I write myself a small script for reading the file ignoring "headers", it runs smoothly, because the structure is regular, and it is also correctly visualised by [https://universaldependencies.org/conllu_viewer.html].

**Comment by EmilStenstrom** [comment]
Since the problem seems to be the spacing between the sentences, I would need to see what separator CoNLL uses too. Could you post an example of this? I'm trying to decide if it similar enough to include in this library or not.

**Comment by Stormur** [comment]
They are really the same, maybe only the type and amount of "headers" (as I am calling sentences introduced by `#`) vary, but the difference is only in the information that you put in each field. I am regularly changing file names from `.conll` to `.conllu` and viceversa to suit the needs of different programs or algorithms.

Also, the reader should probably be insensible to the spacing between sentences, no?

I'm pasting a small CoNLL file:

1	+	+	Punc	Punc	_	0	ROOT	_	_
2	In	in	r	r	r|-|-|-|-|-|-|-|-	5	AuxP	_	_
3	Dei	Deus	n	Propn	n|-|s|-|-|-|m|g|-	4	ATR	_	_
4	nomine	nomen	n	n	n|-|s|-|-|-|n|b|-	2	ADV	_	_
5	regnante	regno	t	t	t|-|s|p|p|a|m|b|-	0	ADV	_	_
6	domno	domnus	n	n	n|-|s|-|-|-|m|b|-	8	ATR	_	_
7	nostro	noster	a	a	a|-|s|-|-|-|m|b|-	6	ATR	_	_
8	Carulo	Carolus	n	Propn	n|-|s|-|-|-|m|b|-	5	SBJ	_	_
9	rege	rex	n	n	n|-|s|-|-|-|m|b|-	8	ATR	_	_
10	Francorum	franci	n	n	n|-|p|-|-|-|m|g|-	11	ATR_CO	_	_
11	et	et	c	c	c|-|-|-|-|-|-|-|-	9	COORD	_	_
12	Langobardorum	langobardi	n	n	n|-|p|-|-|-|m|g|-	11	ATR_CO	_	_
13	,	,	Punc	Punc	_	0	ROOT	_	_
14	anno	annus	n	n	n|-|s|-|-|-|m|b|-	5	ADV	_	_
15	regni	regnum	n	n	n|-|s|-|-|-|n|g|-	14	ATR	_	_
16	eius	is	p	p	p|-|s|-|-|-|m|g|-	15	ATR	_	_
17	quo	qui	p	p	p|-|s|-|-|-|m|b|-	18	ADV	_	_
18	coepit	capio	v	v	v|3|s|r|i|a|-|-|-	14	ATR	_	_
19	Langobardiam	Langobardia	n	Propn	n|-|s|-|-|-|f|a|-	18	OBJ	_	_
20	primo	primus	a	a	a|-|s|-|-|-|m|b|-	14	ATR	_	_
21	,	,	Punc	Punc	_	0	ROOT	_	_
22	septimo	septimus	a	a	a|-|s|-|-|-|m|b|-	23	ATR	_	_
23	decimo	decimus	a	a	a|-|s|-|-|-|m|b|-	5	ADV	_	_
24	kalendas	kalendae	n	n	n|-|p|-|-|-|f|a|-	23	ATR	_	_
25	augustas	augustus	a	a	a|-|p|-|-|-|f|a|-	24	ATR	_	_
26	,	,	Punc	Punc	_	0	ROOT	_	_
27	per	per	r	r	r|-|-|-|-|-|-|-|-	5	AuxP	_	_
28	indictionem	indictio	n	n	n|-|s|-|-|-|f|a|-	27	ADV	_	_
29	duodecimam	duodecimus	a	a	a|-|s|-|-|-|f|a|-	28	ATR	_	_
30	.	.	Punc	Punc	_	0	ROOT	_	_

1	constat	consto	v	v	v|3|s|p|i|a|-|-|-	0	PRED	_	_
2	me	ego	p	p	p|-|s|-|-|-|m|a|-	1	OBJ	_	_
3	Sanitulum	Sanitulus	n	Propn	n|-|s|-|-|-|m|a|-	2	ATR	_	_
4	filium	filius	n	n	n|-|s|-|-|-|m|a|-	3	ATR	_	_
5	quondam	quondam	d	d	d|-|-|-|-|-|-|-|-	6	ATR	_	_
6	Cicchi	Cichus	n	Propn	n|-|s|-|-|-|m|g|-	4	ATR	_	_
7	de	de	r	r	r|-|-|-|-|-|-|-|-	6	AuxP	_	_
8	loco	locus	n	n	n|-|s|-|-|-|m|b|-	7	ATR	_	_
9	Brancalo	Brancalum	n	Propn	n|-|s|-|-|-|n|b|-	8	ATR	_	_
10	praesenti	praesens	a	a	a|-|s|-|-|-|m|b|-	11	ATR	_	_
11	die	dies	n	n	n|-|s|-|-|-|m|b|-	16	ADV	_	_
12	per	per	r	r	r|-|-|-|-|-|-|-|-	16	AuxP	_	_
13	hanc	hic	p	p	p|-|s|-|-|-|f|a|-	14	ATR	_	_
14	cartulam	chartula	n	n	n|-|s|-|-|-|f|a|-	12	ADV	_	_
15	vendere	vendo	v	v	v|-|-|p|n|a|-|-|-	16	OBJ_CO	_	_
16	et	et	c	c	c|-|-|-|-|-|-|-|-	18	COORD	_	_
17	tradere	trado	v	v	v|-|-|p|n|a|-|-|-	16	OBJ_CO	_	_
18	praevideo	praevideo	v	v	v|1|s|p|i|a|-|-|-	1	ExD	_	_
19	tibi	tu	p	p	p|-|s|-|-|-|m|d|-	16	OBJ	_	_
20	Rachiprando	Rachiprandus	n	Propn	n|-|s|-|-|-|m|d|-	19	ATR	_	_
21	presbitero	presbyter	n	n	n|-|s|-|-|-|m|d|-	20	ATR	_	_
22	ecclesiae	ecclesia	n	n	n|-|s|-|-|-|f|g|-	21	ATR	_	_
23	sanctae	sanctus	a	a	a|-|s|-|-|-|f|g|-	24	ATR	_	_
24	Mariae	Maria	n	Propn	n|-|s|-|-|-|f|g|-	22	ATR	_	_
25	sitae	sino	t	t	t|-|s|r|p|p|f|g|-	22	ATR	_	_
26	in	in	r	r	r|-|-|-|-|-|-|-|-	25	AuxP	_	_
27	Sexto	Sextum	n	Propn	n|-|s|-|-|-|n|b|-	26	ADV	_	_
28	duae	duo	a	a	a|-|p|-|-|-|f|n|-	29	ATR	_	_
29	petiae	petia	n	n	n|-|p|-|-|-|f|n|-	16	OBJ	_	_
30	de	de	r	r	r|-|-|-|-|-|-|-|-	29	AuxP	_	_
31	vinea	vinea	n	n	n|-|s|-|-|-|f|b|-	30	ATR	_	_
32	mea	meus	a	a	a|-|s|-|-|-|f|b|-	31	ATR	_	_
33	quam	qui	p	p	p|-|s|-|-|-|f|a|-	34	OBJ	_	_
34	abeo	habeo	v	v	v|1|s|p|i|a|-|-|-	31	ATR	_	_
35	in	in	r	r	r|-|-|-|-|-|-|-|-	34	AuxP	_	_
36	loco	locus	n	n	n|-|s|-|-|-|m|b|-	35	ADV	_	_
37	Metiano	Medianum	n	Propn	n|-|s|-|-|-|n|b|-	36	ATR	_	_
38	;	;	Punc	Punc	_	0	ROOT	_	_

1	una	unus	a	a	a|-|s|-|-|-|f|n|-	2	ATR	_	_
2	petia	petia	n	n	n|-|s|-|-|-|f|n|-	3	SBJ	_	_
3	est	sum	v	v	v|3|s|p|i|a|-|-|-	0	PRED	_	_
4	tenentem	teneo	t	t	t|-|s|p|p|a|f|a|-	3	PNOM	_	_
5	unum	unus	a	a	a|-|s|-|-|-|n|a|-	6	ATR	_	_
6	caput	caput	n	n	n|-|s|-|-|-|n|a|-	23	OBJ_CO	_	_
7	in	in	r	r	r|-|-|-|-|-|-|-|-	6	AuxP	_	_
8	vinea	vinea	n	n	n|-|s|-|-|-|f|b|-	7	ATR	_	_
9	ecclesiae	ecclesia	n	n	n|-|s|-|-|-|f|g|-	12	ATR_CO	_	_
10	sanctae	sanctus	a	a	a|-|s|-|-|-|f|g|-	11	ATR	_	_
11	Mariae	Maria	n	Propn	n|-|s|-|-|-|f|g|-	9	ATR	_	_
12	et	et	c	c	c|-|-|-|-|-|-|-|-	8	COORD	_	_
13	ecclesiae	ecclesia	n	n	n|-|s|-|-|-|f|g|-	12	ATR_CO	_	_
14	sancti	sanctus	a	a	a|-|s|-|-|-|m|g|-	15	ATR	_	_
15	Fridiani	Fridianus	n	Propn	n|-|s|-|-|-|m|g|-	13	ATR	_	_
16	,	,	Punc	Punc	_	0	ROOT	_	_
17	aliud	alius	a	a	a|-|s|-|-|-|n|a|-	18	ATR	_	_
18	caput	caput	n	n	n|-|s|-|-|-|n|a|-	23	OBJ_CO	_	_
19	in	in	r	r	r|-|-|-|-|-|-|-|-	18	AuxP	_	_
20	virgario	virgareum	n	n	n|-|s|-|-|-|n|b|-	19	ATR	_	_
21	sanctae	sanctus	a	a	a|-|s|-|-|-|f|g|-	22	ATR	_	_
22	Mariae	Maria	n	Propn	n|-|s|-|-|-|f|g|-	20	ATR	_	_
23	et	et	c	c	c|-|-|-|-|-|-|-|-	4	COORD	_	_
24	ambo	ambo	p	p	p|-|p|-|-|-|n|a|-	25	ATR	_	_
25	latera	latus^n	n	n	n|-|p|-|-|-|n|a|-	23	OBJ_CO	_	_
26	in	in	r	r	r|-|-|-|-|-|-|-|-	25	AuxP	_	_
27	vinea	vinea	n	n	n|-|s|-|-|-|f|b|-	26	ATR	_	_
28	ipsius	ipse	p	p	p|-|s|-|-|-|f|g|-	29	ATR	_	_
29	ecclesiae	ecclesia	n	n	n|-|s|-|-|-|f|g|-	27	ATR	_	_
30	sanctae	sanctus	a	a	a|-|s|-|-|-|f|g|-	31	ATR	_	_
31	Mariae	Maria	n	Propn	n|-|s|-|-|-|f|g|-	29	ATR	_	_
32	;	;	Punc	Punc	_	0	ROOT	_	_

1	Gheripaldu	Gheiripaldus	n	Propn	n|-|s|-|-|-|m|a|-	19	SBJ	_	_
2	vir	vir	n	n	n|-|s|-|-|-|m|n|-	1	ATR	_	_
3	devotus	devotus	a	a	a|-|s|-|-|-|m|n|-	2	ATR	_	_
4	filio	filius	n	n	n|-|s|-|-|-|m|a|-	1	ATR	_	_
5	quondam	quondam	d	d	d|-|-|-|-|-|-|-|-	6	ATR	_	_
6	Iohanni	Johannes	n	Propn	n|-|s|-|-|-|m|g|-	4	ATR	_	_
7	,	,	Punc	Punc	_	0	ROOT	_	_
8	havitature	habitator	n	n	n|-|s|-|-|-|m|a|-	1	ATR	_	_
9	in	in	r	r	r|-|-|-|-|-|-|-|-	8	AuxP	_	_
10	loco	locus	n	n	n|-|s|-|-|-|m|b|-	9	ADV	_	_
11	qui	qui	p	p	p|-|s|-|-|-|m|n|-	12	SBJ	_	_
12	dicitur	dico	v	v	v|3|s|p|i|p|-|-|-	10	ATR	_	_
13	Monaciaticho	Monaciaticum	n	Propn	n|-|s|-|-|-|n|b|-	12	PNOM	_	_
14	,	,	Punc	Punc	_	0	ROOT	_	_
15	coniugi	conjunx	n	n	n|-|s|-|-|-|f|d|-	18	ATR	_	_
16	sue	suus	a	a	a|-|s|-|-|-|f|d|-	15	ATR	_	_
17	nomine	nomen	n	n	n|-|s|-|-|-|n|b|-	18	ADV	_	_
18	Ermilinda	Ermilinda	n	Propn	n|-|s|-|-|-|f|a|-	19	OBJ	_	_
19	[verb]		Punc	Punc	_	0	PRED	_	_
20	,	,	Punc	Punc	_	0	ROOT	_	_
21	perpetualiter	perpetualis	d	d	d|-|-|-|-|-|-|-|-	19	ADV	_	_
22	.	.	Punc	Punc	_	0	ROOT	_	_

	et	et	c	c	c|-|-|-|-|-|-|-|-	2	ADV	_	_
2	repromitto	repromitto	v	v	v|1|s|p|i|a|-|-|-	16	PRED_CO	_	_
3	ego	ego	p	p	p|-|s|-|-|-|m|n|-	16	SBJ	_	_
4	Filicissimo	Felicissimus	n	Propn	n|-|s|-|-|-|m|a|-	3	ATR	_	_
5	una	unus	d	d	d|-|-|-|-|-|-|-|-	6	AuxY	_	_
6	cum	cum	r	r	r|-|-|-|-|-|-|-|-	2	AuxP	_	_
7	meos	meus	a	a	a|-|p|-|-|-|m|a|-	8	ATR	_	_
8	heredes	heres	n	n	n|-|p|-|-|-|m|a|-	6	ADV	_	_
9	ipsa	ipse	p	p	p|-|s|-|-|-|f|a|-	10	ATR	_	_
10	res	res	n	n	n|-|s|-|-|-|f|a|-	11	OBJ	_	_
11	defensare	defenso	v	v	v|-|-|p|n|a|-|-|-	2	OBJ	_	_
12	ab	ab	r	r	r|-|-|-|-|-|-|-|-	11	AuxP	_	_
13	omni	omnis	a	a	a|-|s|-|-|-|m|b|-	14	ATR	_	_
14	homine	homo	n	n	n|-|s|-|-|-|m|b|-	12	ADV	_	_
15	,	,	Punc	Punc	_	0	ROOT	_	_
16	et	et	c	c	c|-|-|-|-|-|-|-|-	0	COORD	_	_
17	si	si	c	c	c|-|-|-|-|-|-|-|-	22	AuxC	_	_
18	defendere	defendo	v	v	v|-|-|p|n|a|-|-|-	20	OBJ	_	_
19	non	non	d	d	d|-|-|-|-|-|-|-|-	20	AuxZ	_	_
20	potuero	possum	v	v	v|1|s|t|i|a|-|-|-	17	ADV	_	_
21	,	,	Punc	Punc	_	0	ROOT	_	_
22	promitto	promitto	v	v	v|1|s|p|i|a|-|-|-	16	PRED_CO	_	_
23	conponere	compono	v	v	v|-|-|p|n|a|-|-|-	22	OBJ	_	_
24	ipsa	ipse	p	p	p|-|s|-|-|-|f|a|-	26	ATR	_	_
25	suprascripta	suprascriptus	a	a	a|-|s|-|-|-|f|a|-	26	ATR	_	_
26	res	res	n	n	n|-|s|-|-|-|f|a|-	23	OBJ	_	_
27	in	in	r	r	r|-|-|-|-|-|-|-|-	23	AuxP	_	_
28	dupplo	duplus	a	a	a|-|s|-|-|-|n|b|-	27	ADV	_	_
29	,	,	Punc	Punc	_	0	ROOT	_	_
30	in	in	r	r	r|-|-|-|-|-|-|-|-	23	AuxP	_	_
31	ferquidem	ferquidis	a	a	a|-|s|-|-|-|m|b|-	32	ATR	_	_
32	loco	locus	n	n	n|-|s|-|-|-|m|b|-	30	ADV	_	_
33	,	,	Punc	Punc	_	0	ROOT	_	_
34	sub	sub	r	r	r|-|-|-|-|-|-|-|-	23	AuxP	_	_
35	extimatione	aestimatio	n	n	n|-|s|-|-|-|f|b|-	34	ADV	_	_
36	.	.	Punc	Punc	_	0	ROOT	_	_

1	et	et	c	c	c|-|-|-|-|-|-|-|-	2	ADV	_	_
2	volo	volo	v	v	v|1|s|p|i|a|-|-|-	0	PRED	_	_
3	ut	ut	c	c	c|-|-|-|-|-|-|-|-	2	AuxC	_	_
4	pro	pro	r	r	r|-|-|-|-|-|-|-|-	15	AuxP	_	_
5	vestra	vester	a	a	a|-|s|-|-|-|f|b|-	6	ATR	_	_
6	defensione	defensio	n	n	n|-|s|-|-|-|f|b|-	4	ADV	_	_
7	singulis	singulus	a	a	a|-|p|-|-|-|m|b|-	8	ATR	_	_
8	annis	annus	n	n	n|-|p|-|-|-|m|b|-	15	ADV	_	_
9	in	in	r	r	r|-|-|-|-|-|-|-|-	15	AuxP	_	_
10	festivitate	festivitas	n	n	n|-|s|-|-|-|f|b|-	9	ADV	_	_
11	ipsius	ipse	p	p	p|-|s|-|-|-|f|g|-	12	ATR	_	_
12	ecclesie	ecclesia	n	n	n|-|s|-|-|-|f|g|-	10	ATR	_	_
13	sancti	sanctus	a	a	a|-|s|-|-|-|m|g|-	14	ATR	_	_
14	Dalmatii	Dalmatius	n	Propn	n|-|s|-|-|-|m|g|-	12	ATR	_	_
15	reddere	reddo	v	v	v|-|-|p|n|a|-|-|-	16	OBJ	_	_
16	debeatis	debeo	v	v	v|2|p|p|s|a|-|-|-	28	OBJ_CO	_	_
17	episcopo	episcopus	n	n	n|-|s|-|-|-|m|d|-	15	OBJ	_	_
18	qui	qui	p	p	p|-|s|-|-|-|m|n|-	21	SBJ	_	_
19	tunc	tunc	d	d	d|-|-|-|-|-|-|-|-	21	ADV	_	_
20	tempore	tempus	n	n	n|-|s|-|-|-|n|b|-	21	ADV	_	_
21	fuerit	sum	v	v	v|3|s|t|i|a|-|-|-	17	ATR	_	_
22	,	,	Punc	Punc	_	0	ROOT	_	_
23	unum	unus	a	a	a|-|s|-|-|-|m|a|-	24	ATR	_	_
24	soledum	solidus	n	n	n|-|s|-|-|-|m|a|-	15	OBJ	_	_
25	argento	argentum	n	n	n|-|s|-|-|-|n|a|-	24	ATR	_	_
26	bono	bonus	a	a	a|-|s|-|-|-|n|a|-	24	ATR	_	_
27	tantum	tantus	d	d	d|-|-|-|-|-|-|-|-	15	ADV	_	_
28	et	et	c	c	c|-|-|-|-|-|-|-|-	3	COORD	_	_
29	pro	pro	r	r	r|-|-|-|-|-|-|-|-	42	AuxP	_	_
30	vita	vita	n	n	n|-|s|-|-|-|f|b|-	31	ADV_CO	_	_
31	et	et	c	c	c|-|-|-|-|-|-|-|-	29	COORD	_	_
32	salute	salus	n	n	n|-|s|-|-|-|f|b|-	31	ADV_CO	_	_
33	anime	anima	n	n	n|-|s|-|-|-|f|g|-	38	ATR_CO	_	_
34	domni	domnus	n	n	n|-|s|-|-|-|m|g|-	36	ATR	_	_
35	mei	meus	a	a	a|-|s|-|-|-|m|g|-	34	ATR	_	_
36	Iacobi	Iacobus	n	Propn	n|-|s|-|-|-|m|g|-	33	ATR	_	_
37	episcopi	episcopus	n	n	n|-|s|-|-|-|m|g|-	36	ATR	_	_
38	et	et	c	c	c|-|-|-|-|-|-|-|-	31	COORD	_	_
39	mea	meus	a	a	a|-|s|-|-|-|f|b|-	38	ATR_CO	_	_
40	Dominum	Dominus	n	Propn	n|-|s|-|-|-|m|a|-	42	OBJ	_	_
41	adtentius	attentus	d	d	d|-|-|-|-|-|-|-|c	42	ADV	_	_
42	deprecare	deprecor	v	v	v|-|-|p|n|a|-|-|-	43	OBJ	_	_
43	debeatis	debeo	v	v	v|2|p|p|s|a|-|-|-	28	OBJ_CO	_	_
44	,	,	Punc	Punc	_	0	ROOT	_	_
45	eius	is	p	p	p|-|s|-|-|-|m|g|-	47	ATR	_	_
46	postulantes	postulo	t	t	t|-|p|p|p|a|m|n|-	43	AtvV	_	_
47	misericordiam	misericordia	n	n	n|-|s|-|-|-|f|a|-	46	OBJ	_	_
48	,	,	Punc	Punc	_	0	ROOT	_	_
49	ut	ut	c	c	c|-|-|-|-|-|-|-|-	46	AuxC	_	_
50	vitam	vita	n	n	n|-|s|-|-|-|f|a|-	52	OBJ	_	_
51	eternam	aeternus	a	a	a|-|s|-|-|-|f|a|-	50	ATR	_	_
52	consequi	consequor	v	v	v|-|-|p|n|p|-|-|-	53	OBJ	_	_
53	mereamur	mereor	v	v	v|1|p|p|s|p|-|-|-	49	ADV	_	_
54	.	.	Punc	Punc	_	0	ROOT	_	_

1	et	et	c	c	c|-|-|-|-|-|-|-|-	5	ADV	_	_
2	qui	qui	p	p	p|-|s|-|-|-|m|n|-	5	SBJ	_	_
3	hoc	hic	p	p	p|-|s|-|-|-|n|a|-	4	OBJ	_	_
4	facere	facio	v	v	v|-|-|p|n|a|-|-|-	5	OBJ	_	_
5	neclexerit	neglego	v	v	v|3|s|t|i|a|-|-|-	10	SBJ	_	_
6	a	ab	r	r	r|-|-|-|-|-|-|-|-	10	AuxP	_	_
7	Deo	Deus	n	Propn	n|-|s|-|-|-|m|b|-	6	OBJ	_	_
8	se	se	p	p	p|-|s|-|-|-|m|a|-	10	OBJ	_	_
9	sia	sum	v	v	v|3|s|p|s|a|-|-|-	10	AuxV	_	_
10	damnatum	damno	t	t	t|-|s|r|p|p|m|a|-	0	PRED	_	_
11	pro	pro	r	r	r|-|-|-|-|-|-|-|-	10	AuxP	_	_
12	ipsa	ipse	p	p	p|-|s|-|-|-|f|b|-	14	ATR	_	_
13	sua	suus	a	a	a|-|s|-|-|-|f|b|-	14	ATR	_	_
14	negligentia	neglegentia	n	n	n|-|s|-|-|-|f|b|-	11	ADV	_	_
15	.	.	Punc	Punc	_	0	ROOT	_	_

1	et	et	c	c	c|-|-|-|-|-|-|-|-	9	ADV	_	_
2	in	in	r	r	r|-|-|-|-|-|-|-|-	7	AuxP	_	_
3	festivitatibus	festivitas	n	n	n|-|p|-|-|-|f|b|-	2	ADV	_	_
4	sancte	sanctus	a	a	a|-|s|-|-|-|f|g|-	5	ATR	_	_
5	Marie	Maria	n	Propn	n|-|s|-|-|-|f|g|-	3	ATR	_	_
6	reddere	reddo	v	v	v|-|-|p|n|a|-|-|-	7	OBJ_CO	_	_
7	et	et	c	c	c|-|-|-|-|-|-|-|-	9	COORD	_	_
8	dare	do	v	v	v|-|-|p|n|a|-|-|-	7	OBJ_CO	_	_
9	debuissent	debeo	v	v	v|3|p|l|s|a|-|-|-	0	PRED	_	_
10	ad	ad	r	r	r|-|-|-|-|-|-|-|-	14	AuxP	_	_
11	primicerium	primicerius	n	n	n|-|s|-|-|-|m|a|-	10	OBJ_CO	_	_
12	eius	is	p	p	p|-|s|-|-|-|m|g|-	11	ATR	_	_
13	,	,	Punc	Punc	_	0	ROOT	_	_
14	vel	vel	c	c	c|-|-|-|-|-|-|-|-	7	COORD	_	_
15	quale	qualis	a	a	a|-|s|-|-|-|m|a|-	16	ATR	_	_
16	misso	missus	n	n	n|-|s|-|-|-|m|a|-	19	OBJ	_	_
17	illis	ille	p	p	p|-|p|-|-|-|m|n|-	19	SBJ	_	_
18	ibi	ibi	d	d	d|-|-|-|-|-|-|-|-	19	ADV	_	_
19	direxissent	dirigo	v	v	v|3|p|l|s|a|-|-|-	14	OBJ_CO	_	_
20	,	,	Punc	Punc	_	0	ROOT	_	_
21	medietatem	medietas	n	n	n|-|s|-|-|-|f|a|-	7	OBJ	_	_
22	offertas	offertum	n	n	n|-|p|-|-|-|n|a|-	23	ATR_CO	_	_
23	et	et	c	c	c|-|-|-|-|-|-|-|-	21	COORD	_	_
24	candelas	candela	n	n	n|-|p|-|-|-|f|a|-	23	ATR_CO	_	_
25	,	,	Punc	Punc	_	0	ROOT	_	_
26	que	qui	p	p	p|-|p|-|-|-|f|n|-	32	SBJ	_	_
27	in	in	r	r	r|-|-|-|-|-|-|-|-	32	AuxP	_	_
28	eius	is	p	p	p|-|s|-|-|-|f|g|-	29	ATR	_	_
29	festivitatibus	festivitas	n	n	n|-|p|-|-|-|f|b|-	27	ADV	_	_
30	ibi	ibi	d	d	d|-|-|-|-|-|-|-|-	32	ADV	_	_
31	datas	do	t	t	t|-|p|r|p|p|f|a|-	32	ATR_CO	_	_
32	et	et	c	c	c|-|-|-|-|-|-|-|-	23	COORD	_	_
33	offertas	offero	t	t	t|-|p|r|p|p|f|a|-	32	ATR_CO	_	_
34	fuissent	sum	v	v	v|3|p|l|s|a|-|-|-	32	AuxV	_	_
35	,	,	Punc	Punc	_	0	ROOT	_	_
36	de	de	r	r	r|-|-|-|-|-|-|-|-	7	AuxP	_	_
37	ipsa	ipse	p	p	p|-|s|-|-|-|f|b|-	39	ATR	_	_
38	suorum	suus	a	a	a|-|p|-|-|-|m|g|-	39	ATR	_	_
39	portionem	portio	n	n	n|-|s|-|-|-|f|b|-	36	ADV	_	_
40	;	;	Punc	Punc	_	0	ROOT	_	_

**Comment by EmilStenstrom** [comment]
Thanks for a good example! I'll have a look in the coming weeks and see if this is something that is fixable as part of this library or not!

**Comment by EmilStenstrom** [comment]
Ok, so I've tested that the example above can be parsed with conllu. Here's a testcase using your example: https://github.com/EmilStenstrom/conllu/blob/master/tests/test_integration.py#L236

The `field_parsers`-part is optional, I just wanted to play with getting the feats field as a list.
