### ISSUE TITLE
Column 'deps' is not being parsed most of the time

### ISSUE THREAD

**Issue by flennic** [EmilStenstrom/conllu#34]
Given the following sentence:

```
Removed.
```

The code at `parser.py:152` looks like this:

```python
def parse_paired_list_value(value):
    if fullmatch(MULTI_DEPS_PATTERN, value):
        return [
            (part.split(":", 1)[1], parse_id_value(part.split(":")[0]))
            for part in value.split("|")
        ]

    return parse_nullable_value(value)
```

Is seems like the definition of `MULTI_DEPS_PATTERN` is not correct. Most `deps` values are returned as strings instead of a list of tuples, because the parsing fails. For example `'1:compound|6:ARG1|9:ARG1'` is considered bad, but according to [the specification](https://universaldependencies.org/format.html#syntactic-annotation) this should be alright. Actually the code for parsing inside of the if-statement works perfectly on this line. `'4:ARG1'` is also being considered flawed, but `'5:measure'` is being considered okay.

**Comment by EmilStenstrom** [comment]
Thanks for a great bug report!

Looking at the specification, and the values seem to be specified under [Syntactic Annotation](https://universaldependencies.org/format.html#syntactic-annotation): 

> The dependency relations in DEPREL must have the form [a-z]+(:[a-z]+)?. 

Maybe I'm reading this wrong, but "ARG1" has uppercase letters and numbers, so doesn't conform to the above format?

I would be fine however to add support for uppercase and number in that regex. I don't see how that would reduce the accuracy of valid files, and it would support more non-generic ones.

Would you mind writing up a PR for this?

**Comment by flennic** [comment]
Hej Emil,

you are right, the specification does not support capitalized letters. Somehow I didn't read that part, shame on me! As you started the project I think it is up to you if you want to "strictly" follow the specification or if you want to allow "small" differences for more usability.

If your answer is yes, i am happy to create a PR for this. Let me know your answer.

flennic

**Comment by EmilStenstrom** [comment]
I’m fine with allowing more than the specification does!

**Comment by flennic** [comment]
I've not forgotten to create the PR, will do it as soon as I have time for it, probably the weekend or in the beginning of next week.

**Comment by EmilStenstrom** [comment]
No rush, we’re all working on our free time!
