### ISSUE TITLE
Support for unstructured comments

### ISSUE THREAD

**Issue by kawu** [EmilStenstrom/conllu#37]
According to the [format specification](https://universaldependencies.org/format.html#paragraph-and-document-boundaries), comments such as `# newdoc` should be allowed.  However, when I try to parse and serialize the following text:
```
# newdoc
# sent_id = 1
# text = They buy and sell books.
1   They     they    PRON    PRP    Case=Nom|Number=Plur               2   nsubj   2:nsubj|4:nsubj   _
2   buy      buy     VERB    VBP    Number=Plur|Person=3|Tense=Pres    0   root    0:root            _
3   and      and     CONJ    CC     _                                  4   cc      4:cc              _
4   sell     sell    VERB    VBP    Number=Plur|Person=3|Tense=Pres    2   conj    0:root|2:conj     _
5   books    book    NOUN    NNS    Number=Plur                        2   obj     2:obj|4:obj       SpaceAfter=No
6   .        .       PUNCT   .      _                                  2   punct   2:punct           _

```
serialization throws the `TypeError: must be str, not NoneType` exception.  Parsing works fine, I'm able to retrieve the metadata for the sentence above:
```
>>> sent.metadata                                                                                                                                                                                             
OrderedDict([('newdoc', None),
             ('sent_id', '1'),
             ('text', 'They buy and sell books.')])
```

Would it be possible to add support for such unstructured comments?

**Comment by EmilStenstrom** [comment]
@kawu Thanks for reporting! This is an error on my part.

I've fixed the problem, added tests so it can't happen again, and released a new version to PyPI: https://pypi.org/project/conllu/2.2.2/

**Comment by EmilStenstrom** [comment]
Here's the code that fixes the error: https://github.com/EmilStenstrom/conllu/commit/626de1dd1bb927ef4e8a852d706fda7281d818d4

**Comment by kawu** [comment]
That was quick, thank you @EmilStenstrom!
