### ISSUE TITLE
Allow for multiple root nodes

### ISSUE THREAD

**Issue by hatzel** [EmilStenstrom/conllu#44]
This is probably not strictly speaking an issue with this library so feel free to close the issue.

While using [ParZu](https://github.com/rsennrich/ParZu) I came across the issue that most outputs define multiple root nodes. Take the example sentence "Ich esse einen Apfel." ("I eat an apple")

ParZu's output for this looks something like this:
```
1	Ich	ich	PRO	PPER	1|Sg|_|Nom	2	subj	_	_
2	esse	essen	V	VVFIN	1|Sg|Pres|_	0	root	_	_
3	einen	eine	ART	ART	Indef|Masc|Acc|Sg	4	det	_	_
4	Apfel	Apfel	N	NN	Masc|Acc|Sg	2	obja	_	_
5	.	.	$.	$.	_	0	root	_	_
```
Both the verb and the punctuation claim to be root.

I did write a [quick workaround](https://github.com/hatzel/conllu/commit/0b1574cb3c2666c398da8e478ce56823061c0219). It just creates a top level `ROOT` node for `root` nodes to attach to.

The patch is probably not fit for inclusion in its current state. If you do have some specific ideas of how the problem of multiple root's like this could be merged I'd be open to that. If not that's fine as well, maybe this issue will help someone out some day ;)

**Comment by EmilStenstrom** [comment]
Thanks for posting! I think I'll add your fix to the library. As you say, it's not technically a valid document, but I'd like conllu to be more generous that the spec allows.

**Comment by EmilStenstrom** [comment]
I just released conllu 4.2 with your additions! https://pypi.org/project/conllu/

**Comment by hatzel** [comment]
Thanks for the swift response and just this library in general!

**Comment by jheinecke** [comment]
I still observe a strange thing, possibly linked to this workaround: If there are more than two tokens with head 0 in a conllu sentence and I try to get the upos of the sentence root (the top level one), I get a maximum recursion error.
for example the following script reproduces the error:

```
#!/usr/bin/env python3

sent = """1	the	the	DET	_	_	0	root	_	_
2	mouse	mouse	NOUN	_	_	3	root	_	_
3	sleeps	sleep	VERB	_	_	0	root	_	_

"""

for sentence in conllu.parse(sent):
    #print(sentence)
    root = sentence.to_tree()
    root.print_tree()
    print(root.token)
    print(root.token["upos"])
```

Running it gives the following error message
```
(deprel:root) form:_ [0]  # <-- the toplevel root does not have an  UPOS
    (deprel:root) form:the lemma:the upos:DET [1]
    (deprel:root) form:sleeps lemma:sleep upos:VERB [3]
        (deprel:root) form:mouse lemma:mouse upos:NOUN [2]
{'id': 0, 'form': '_', 'deprel': 'root'}
Traceback (most recent call last):
  File "./ex.py", line 15, in <module>
    print(root.token["upos"])
  File "/home/jh/.local/lib/python3.6/site-packages/conllu/models.py", line 31, in __missing__
    return self[self.MAPPING[key]]
  File "/home/jh/.local/lib/python3.6/site-packages/conllu/models.py", line 31, in __missing__
    return self[self.MAPPING[key]]
  File "/home/jh/.local/lib/python3.6/site-packages/conllu/models.py", line 31, in __missing__
    return self[self.MAPPING[key]]
  [Previous line repeated 246 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by jheinecke** [comment]
I had more time to look at the code. If I had used  `print(root.token.get("upos")` the error would not have occured. The problem is the (circular) definition of `MAPPING` in the ` class Token(dict)`  (conllu/models.py:15)
```
class Token(dict):
     MAPPING = {
         "upostag": "upos",
         "xpostag": "xpos",
         "upos": "upostag",
         "xpos": "xpostag",
     }
...
```
The `__missing__()` function does not find the key `upos` and tries `upostag`. When it does not find the key `upostag` neither it restarts trying `upos` etc until the RecursionError occurs. Not sure what would be the most inteliigent solution, I think dropping `"upos": "upostag"` and `"xpos": "xpostag"` would be OK, since `upos` is the key for more often used in the wild
