### ISSUE TITLE
Add a `__next__()` method to `TokenList` ?

### ISSUE THREAD

**Issue by plefebvre91** [EmilStenstrom/conllu#52]
Hi,

Maybe adding a `__next__()` method to the `TokenList` type could be interesting. Currently when the TokenList is transformed into an iterator with `iter()`, `next(my_list)` returns only the first element of the tuple (`id`/`form`/`lemma`/etc.).

**Comment by EmilStenstrom** [comment]
Hi! Yes, this would be a nice addition! Would you mind contributing a patch? Preferably with tests :)

**Comment by plefebvre91** [comment]
Oups, I probably got a bit confused, it seems it already do the job :confused:  (The unit test I was writing was OK before I wrote the code :expressionless: ).

**Comment by EmilStenstrom** [comment]
That’s a good thing!
