### ISSUE TITLE
CoNLL-U Plus: Retain global.columns when slicing

### ISSUE THREAD

**Issue by arademaker** [EmilStenstrom/conllu#53]
Do you have plans to support the https://universaldependencies.org/ext-format.html?

**Comment by EmilStenstrom** [comment]
It is supported! Are you missing something?

**Comment by EmilStenstrom** [comment]
And to answer your next question: all that not in comments are available in the metadata attribute of a sentence: https://github.com/EmilStenstrom/conllu

CoNLL-U also supports specifying columns as a comment, and this is also supported.

**Comment by arademaker** [comment]
Thank you. Not sure if I understood the second point. columns as a comment? 

Regarding the conllup format: 

> In particular, there is a comment that is defined in the extension CoNLL-U Plus, global.columns, which must appear as the first line of a CoNLL-U Plus file; while this comment is not part of the basic CoNLL-U specification, it is recommended that processing tools keep it as the first line if it is present. In general, it is recommended that tools keep the order of the comments unless they are specifically designed to modify it.

```
(venv) ar@tenis UD_Portuguese-Bosque % python
Python 3.9.6 (default, Jun 29 2021, 05:25:02)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from conllu import parse
>>> with open("pt_bosque-ud-dev.conllup", "r", encoding="utf-8") as df: txt = df.read()
...
>>> sentences = parse(txt)
>>> sentences[0].metadata
{'global.columns': 'ID FORM LEMMA UPOS XPOS FEATS HEAD DEPREL DEPS MISC DEEP:PRED DEEP:ARGS', 'text': 'É dele o segundo lugar do Smirnoff International Fashion Awards, disputado anteontem em Dublin.', 'source_sent_id': 'conllu http://hdl.handle.net/11234/1-3105 UD_Portuguese-Bosque/pt_bosque-ud-dev.conllu CF892-3', 'sent_id': 'CF892-3', 'source': 'CETENFolha n=892 cad=Ilustrada sec=nd sem=94a', 'id': '3759'}
>>> sentences[1].metadata
{'text': 'Um Godard intergaláctico', 'source_sent_id': 'conllu http://hdl.handle.net/11234/1-3105 UD_Portuguese-Bosque/pt_bosque-ud-dev.conllu CF893-1', 'sent_id': 'CF893-1', 'source': 'CETENFolha n=893 cad=TV Folha sec=clt-soc sem=94b', 'id': '3760'}
```

The `global.columns` should have to be propagated to all the sentences in the file, right?

**Comment by arademaker** [comment]
I mean, in the current version, If I open an conllup and serialize a subset of the sentences, I need to introduce the metadata in the first sentence myself. In the code below, the final `lixo.conllup` does not contain the `global.columns`... 

```python
from conllu import parse
with open("pt_bosque-ud-dev.conllup", "r", encoding="utf-8") as df: 
  txt = df.read()
sentences = parse(txt)
with open('lixo.conllup', 'w') as f: 
  f.writelines([sentence.serialize() + "\n" for sentence in sentences[2:4]])
```

**Comment by EmilStenstrom** [comment]
@arademaker Oh, right, good catch. That does look like a bug. global.columns should set attributes on document level, not on sentence label. This should be fixed.

If you are able, I'd love to see a PR that fixes this, if not, I'll leave this open and get to it as soon as I have a moment of hacking time available! :)

**Comment by EmilStenstrom** [comment]
@arademaker So looking more into this. I was worried the columns didn't propagate from the first sentence to all other sentences in the same file, but this seems to work fine. What's left is when serializing a subset of a parsed file as you describe above.

I see two ways this could be solved:
* We could introduce a new class that mimics a python list, but that also contains CoNNL-U Plus columns saved as metadata. This would mean that parse() returns that object instead of a list. When slicing that object the metadata would be retained in the returned slice, and therefore included in the serialization. 
* Another way would be to propagate the column into to each sentence, and then only output the column data for the first sentence when serializing. 

Not sure which way would be best in this case, opinions welcome :)

I think both ways should be possible to do without breaking backwards compatibility.

**Comment by harisont** [comment]
Hej! I used you library to write a script that converts between CoNNL-U Plus and plain CoNNL-U and noticed the same. Are you planning to fix this anytime soon? Otherwise I might give it a try if I have time.

**Comment by EmilStenstrom** [comment]
@harisont I'm not planning to work on this any time soon, so happy to accept contributions! When working on this, try to keep backwards compatibility as much as possible!

**Comment by EmilStenstrom** [comment]
After a lot more work than I anticipated, slicing a parsed document now retains metadata. I hope that this will more closely work like one would expect. Thanks for reporting, and feel free to raise issues if you feel things doesn't work like expected.

https://pypi.org/project/conllu/4.5/
