### ISSUE TITLE
Blank line check is not robust

### ISSUE THREAD

**Issue by bminixhofer** [EmilStenstrom/conllu#54]
Thanks for this library!

The check for a blank line:

https://github.com/EmilStenstrom/conllu/blob/70b144beb205ac961d6b43f01bc162e947add9e2/conllu/parser.py#L55

is not robust. I am working with the data from WNUT 2017 (https://noisy-text.github.io/2017/emerging-rare-entities.html) were blank lines are denoted as `\t\n` so it fails. From what I could find, the CONLL Format only specifies "blank line" as sentence separator, so I believe the best check would be 

```python
if len(line.strip()) == 0
```

What's your thoughts on this?

**Comment by EmilStenstrom** [comment]
Makes sense to me. I think having the check be line.strip() == “” is clearer still.

Would you mind making a PR?

**Comment by EmilStenstrom** [comment]
A fix for this was released as part of conllu==4.4.1
