### ISSUE TITLE
enhanced dependencies

### ISSUE THREAD

**Issue by arademaker** [EmilStenstrom/conllu#57]
Read column 9 and make the enhanced dependency graph available?

**Comment by EmilStenstrom** [comment]
@arademaker Could you elaborate? What’s the need, why do you need it, how would it work?

**Comment by arademaker** [comment]
Sorry, I just noticed that you already parse column 9 constructing a list of pairs. 

```python
>>> data_file = open("all.conllu", "r", encoding="utf-8")
>>> sentences = [x for x in parse_incr(data_file)]
>>> sentences[0]
TokenList<É, dele, de, ele, o, segundo, lugar, do, de, o, Smirnoff, International, Fashion, Awards, ,, disputado, anteontem, em, Dublin, .>
>>> sentences[0][2]
{'id': 2, 'form': 'de', 'lemma': 'de', 'upos': 'ADP', 'xpos': None, 'feats': None, 'head': 3, 'deprel': 'case', 'deps': [('case', 3)], 'misc': None}
>>> data_file = open("all.conllu", "r", encoding="utf-8")
>>> sentences = [x for x in parse_tree_incr(data_file)]
>>> sentences[0]
TokenTree<token={id=3, form=ele}, children=[...]>
>>> sentences[0].token
{'id': 3, 'form': 'ele', 'lemma': 'ele', 'upos': 'PRON', 'xpos': None, 'feats': {'Gender': 'Masc', 'Number': 'Sing', 'Person': '3', 'PronType': 'Prs'}, 'head': 0, 'deprel': 'root', 'deps': [('root', 0)], 'misc': None}
```

Maybe this is the correct/adequate level of abstraction consistent with the library goals. I was thinking of more methods around the basic data structures: TokenList and TokenTree. For instance, a TokenTree has a token and children fields. The enhanced dependencies suggest a Graph, with few more methods since a Token now can contain more than one head. 

Suppose I want to make a query for the cases https://ufal.mff.cuni.cz/deep-universal-dependencies/deep-ud-stats-external-subjects:

> A node is counted as an external subject if it has two or more parents, one of them is connected via a subject relation, the other is connected either via a subject relation or via an object relation, and at the same time the first parent is attached to the second parent via an xcomp relation.

**Comment by EmilStenstrom** [comment]
Hi again,

I think this is a too advanced use-case for conllu. I think the easiest way forward would be to parse with conllu, take the result into a graph database of some kind (neo4j?) and write graph queries against that database that correspond to what your are looking for. Does that make sense?
