### ISSUE TITLE
Integrating with NLTK?

### ISSUE THREAD

**Issue by Geremia** [EmilStenstrom/conllu#58]
Can `conllu` be integrated with [NLTK](https://www.nltk.org/_modules/nltk/corpus/reader/conll)?
NLTK has a [ConllCorpusReader class](https://www.nltk.org/_modules/nltk/corpus/reader/conll), but [it currently doesn't support CoNLL-U](https://stackoverflow.com/q/66563494/1429450).

**Comment by EmilStenstrom** [comment]
@Geremia I think that should be possible, though with some work to map between the two formats. The output of conllu is much simpler than the NLTK version. Is there an example somewhere on how that ConlluCorpusReader class is used? How are you using it?

**Comment by arademaker** [comment]
Maybe http://www.nltk.org/howto/dependency.html ?

**Comment by EmilStenstrom** [comment]
@arademaker Thanks! But ConlluCorpusReader doesn't seem to be used directly in that case. I would guess that DependencyGraph somehow internally references ConlluCorpusReader, maybe hardcoded? In that case updating NLTK itself would be needed to get CoNNL-U working inside NLTK.

I'm open to working with the NLTK team to use the conllu library to improve support. Do we have a contact within that team that we can talk to, to get the ball rolling?
