### ISSUE TITLE
Multiword tokens

### ISSUE THREAD

**Issue by jheinecke** [EmilStenstrom/conllu#62]
Hi,

does the conllu package process MWT tokens, lke French _du_ which is a contraction of _de_ and _le_:

```
1-2	du	_	_	...
1	de	de	ADP	...
2	le	le	DET	...
```

conllu seems to read them without error but the MWT tokens are not accessible (and `serialize()` omits them)

**Comment by jheinecke** [comment]
OK, with `parse(data)` I see the MWTs, However I used `parse_tree(data)`, since I need the tree structure and there the MWTs are gone

**Comment by EmilStenstrom** [comment]
Sorry for the late reply. The tree structure are constructed from pointers from specific ID:s to other ID:s. Since MWT:s do not have one but many ID:s, where do you think they should reside in the tree?

**Comment by jheinecke** [comment]
You could add them either to the first ID, or to all or just somewhere in the tree that they come out when calling `serialize()`?

**Comment by EmilStenstrom** [comment]
I've thought this through, and I don't think MWT:s belong in the tree. They would require special handling both when parsing and when serializing, and would likely not fit what people where expecting.

Suggestion for how to handle this instead: Do two passes over each sentence. The first just to put each MWT in a dict by the index you want to look it up by (the first ID?). In the second pass, you go through the parse three, and can then easily look up if this tree node is part of a MWT by looking up the ID in the MWT dict. Does this work for you use-case?

**Comment by jheinecke** [comment]
Yes I do something similar: I use two structures, the simple parsing (with the MWTs) and from this I create the dependency tree, for serialisation I recombine  both (texxt and tokens from `parse()`, deprels and heads from `parse_tree()`

**Comment by EmilStenstrom** [comment]
Seems like a reasonable workaround. I’ll close this for now.
