### ISSUE TITLE
hidden breaking change in conllu 4.4.3 and 4.5.0

### ISSUE THREAD

**Issue by helpmefindaname** [EmilStenstrom/conllu#68]
Hi,

First, thank you for creating this awesome parser!

Users of the Flair library, have [an issue](https://github.com/flairNLP/flair/issues/2859) with the released versions from yesterday.
The issue is that `conllu.TokenList` cannot be imported anymore, but needs to change to `conllu.models.TokenList`.

As I suppose, that not only flair runs into the issue, I would suggest adding `from conllu.models import TokenList` in the conllu `__init__.py` and releasing a hotfix.

On long term, it would be nice to add an `__all__` tag to specify the [public interface](https://peps.python.org/pep-0008/#public-and-internal-interfaces), so it would be clear that `conllu.TokenList` wasn't intended to be used that way.

**Comment by EmilStenstrom** [comment]
Thank you for reporting this. I just released 4.5.1 which makes TokenList available as an import directly from conllu, and declares the public API via `__all__`. This should fix the flair issues if I understand things correctly?

**Comment by helpmefindaname** [comment]
Thank you for the quick response and fix, now everything works as intended
