### ISSUE TITLE
Fields with HEAD = -1 are excluded from the parse tree

### ISSUE THREAD

**Issue by jamesqo** [EmilStenstrom/conllu#7]
I'm not sure whether this is intentional, but it's causing problems for my app since I want to include these nodes at root nodes of the parse tree. Simply doing `contents.replace('-1', '0')` won't do it since I only want to include particular nodes based on their `upostag` field.

The problematic line is this: https://github.com/EmilStenstrom/conllu/blob/master/conllu/parser.py#L83. `'-1'.isdigit()` returns false.

**Comment by EmilStenstrom** [comment]
Hi again. I'm not sure if you are using conllu any longer, but I've decided to remove negative nodes when building a tree again. Looking at how people use negative nodes, they seem to be used to indicate that a token should NOT be included, so I've decided to make conllu do that too. If you want to restore the old behaviour, add the nodes you want in the tree back manually, by appending to root.children manually.

Or, you could use a version before 1.4, where this was changed.

Sorry for any inconvenience this means for you.
