### ISSUE TITLE
5.0.0 wheel on PyPI is empty

### ISSUE THREAD

**Issue by asumagic** [EmilStenstrom/conllu#96]
Hello,

Just a heads up, in case you haven't noticed yet: the `5.0.0` wheel on PyPI is empty (probably due to a project build config issue), thus, currently, installing the latest conllu through `pip` results in a missing `conllu` module.

Good luck :)

**Comment by Guust-Franssens** [comment]
Yep same issue here.

**Comment by EmilStenstrom** [comment]
@asumagic @Guust-Franssens Thanks for reporting. I was migrating from setup.py to pyproject.toml and didn't verify things enough. I've now removed 5.0.0 and released 5.0.1: https://pypi.org/project/conllu/ - If you can verify that everything works as intended I'd be very thankful!

**Comment by Guust-Franssens** [comment]
LGTM!

```bash
> pip install conllu
Collecting conllu
  Downloading conllu-5.0.1-py3-none-any.whl.metadata (21 kB)
Downloading conllu-5.0.1-py3-none-any.whl (16 kB)
Installing collected packages: conllu
Successfully installed conllu-5.0.1

> python
Python 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import conllu
>>> 
```

**Comment by EmilStenstrom** [comment]
@Guust-Franssens THANKS!
