### ISSUE TITLE
Failure with serializing/deserializing using Python `pickle`

### ISSUE THREAD

**Issue by aalok-sathe** [EmilStenstrom/conllu#97]
I think something may be broken when serializing (pickle-dumping) and loading back conllu-parsed sentences.
```python
File "python3.9/site-packages/conllu/models.py", line 103, in extend
    self.metadata.update(iterable.metadata)
AttributeError: 'TokenList' object has no attribute 'metadata'
```

**Comment by EmilStenstrom** [comment]
@aalok-sathe Thanks for reporting. Can you set up a little testcase to show what code isn't working?

**Comment by aalok-sathe** [comment]
```python

txt = '''
# conllu-formatted text here
'''

parsed = conllu.parse(txt)

# the serializing happens fine
with open('./parsed.pkl', 'wb') as f:
    pickle.dump(parsed, f)

# but, we get an error here trying to read it back:
with open('./parsed.pkl', 'rb') as f:
    parsed = pickle.load(f)

# instead, if we call `.to_tree()` first, the dumping and loading both work fine!
with open('./parsed.pkl', 'wb') as f:
    pickle.dump(list(map(lambda x: x.to_tree(), parsed)), f)
```

**Comment by kylebgorman** [comment]
Also bit by this bug.

**Comment by kylebgorman** [comment]
[This patch](https://github.com/EmilStenstrom/conllu/commit/32f7d119e152a26dc62c278aac93e8f55954b13d) is my attempt to sidestep the issue, though I have no deeper understanding.

**Comment by EmilStenstrom** [comment]
@kylebgorman Thansk! Mind adding a test that makes sure we don't break serialization in the future?

**Comment by kylebgorman** [comment]
Sure. Let me note something that may or may not be related: I am finding that the `TokenList.filter` method also drops the metadata (though it looks like it wouldn't). Is this WAI or not? It may be related.

**Comment by EmilStenstrom** [comment]
@kylebgorman that's not on purpose, likely something I've just missed...
